yup

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,3 +1,39 @@
+# ------------------------
+# zplugin (plugin manager)
+# ------------------------
+
+declare -A ZPLGM  # initial Zplugin's hash definition, if configuring before loading Zplugin, and then:
+
+ZPLGM[HOME_DIR]="${XDG_DATA_HOME:-$HOME/.local/share}/zplugin"
+ZPLGM[ZCOMPDUMP_PATH]=$ZDOTDIR/.zcompdump
+ZPFX="${ZPLGM[HOME_DIR]}/polaris"
+# => ZPFX (polaris) directory to store compiled programs
+[ -d $ZPFX/bin ] || mkdir -p $ZPFX/bin
+
+# ==> bootstrapper
+if [[ ! -d "${ZPLGM[HOME_DIR]}/bin" ]]; then
+  if (( $+commands[git] )); then
+    git clone https://github.com/zdharma/zplugin.git ${ZPLGM[HOME_DIR]}/bin
+  else
+    echo 'git not found' >&2
+    return 1
+  fi
+fi
+
+# ==> zplugin automatic compilation module
+#     lets you use source-study module to check load times
+#     (call with `zpmod source-study`)
+if [[ -d "${ZPLGM[HOME_DIR]}/bin/zmodules/Src"  ]] ; then
+  module_path+=( "${ZPLGM[HOME_DIR]}/bin/zmodules/Src" )
+  # run in subshell to avoid error outputs (e.g. when it attempts to create
+  # .zwc files in system paths)
+  # this will compile zsh scripts but won't load the module in this shell
+  # so `zpmod source-study` won't work
+  (zmodload zdharma/zplugin) > /dev/null 2>&1
+fi
+
+source "${ZPLGM[HOME_DIR]}/bin/zplugin.zsh"
+
 # =============================================================================
 # Setup
 # =============================================================================
@@ -9,22 +45,6 @@ fi
 local CASK_HOME="/usr/local/Homebrew/Library/Taps"
 local FORMULA_HOME="/usr/local/Cellar"
 
-declare -A ZPLGM  # initial Zplugin's hash definition, if configuring before loading Zplugin, and then:
-
-ZPLGM[HOME_DIR]="${XDG_DATA_HOME:-$HOME/.local/share}/zplugin"
-ZPLGM[ZCOMPDUMP_PATH]=$ZDOTDIR/.zcompdump
-ZPFX="${ZPLGM[HOME_DIR]}/polaris"
-# => ZPFX (polaris) directory to store compiled programs
-[ -d $ZPFX/bin ] || mkdir -p $ZPFX/bin
-
-# ==> zplugin automatic compilation module
-#     lets you use source-study module to check load times
-#     (call with `zpmod source-study`)
-if [[ -d "${ZPLGM[HOME_DIR]}/bin/zmodules/Src"  ]] ; then
-  module_path+=( "${ZPLGM[HOME_DIR]}/bin/zmodules/Src" )
-  (zmodload zdharma/zplugin) >/dev/null 2>&1
-fi
-
 # -------------
 # gpg ssh agent
 # -------------
@@ -32,20 +52,6 @@ if [[ $OSTYPE == linux* ]]; then
   unset SSH_AGENT_PID
   if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
     export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
-  fi
-fi
-
-# ------------------------
-# zplugin (plugin manager)
-# ------------------------
-
-# ==> bootstrapper
-if [[ ! -d "${ZPLGM[HOME_DIR]}/bin" ]]; then
-  if (( $+commands[git] )); then
-    git clone https://github.com/zdharma/zplugin.git ${ZPLGM[HOME_DIR]}/bin
-  else
-    echo 'git not found' >&2
-    return 1
   fi
 fi
 
@@ -95,8 +101,8 @@ setopt NO_CHECK_JOBS
 # -------
 # ==> cp/mv
 #     prompt for overwrite; displays changes
-# alias cp='cp -iv'
-# alias mv='mv -iv'
+alias cp='cp -iv'
+alias mv='mv -iv'
 
 # ==> mkdir
 #     create intermediate directories; display created directories
@@ -110,8 +116,8 @@ alias mkdir='mkdir -pv'
 #     c: repaint screen from top-down (rather than bottom-up)
 alias less='less -SRF'
 
-alias v='nvim'
 alias n='nvim'
+alias v='vim'
 
 # ----------------
 # install programs
@@ -134,20 +140,19 @@ source ~/.colors/base16_profile_helper.sh # call before prompt because this chec
 # Plugins
 # =============================================================================
 
-source "${ZPLGM[HOME_DIR]}/bin/zplugin.zsh"
-
 # --------------
 # custom plugins
 # --------------
 # ==> plugins
 # glob qualifiers: `.` for regular files; `N` for `null_glob`
-zplugin snippet "$ZDOTDIR/plugins/cp-mv-safe.plugin.zsh"
-zplugin snippet "$ZDOTDIR/plugins/git.plugin.zsh"
 zplugin snippet "$ZDOTDIR/plugins/keybindings.plugin.zsh"
 zplugin snippet "$ZDOTDIR/plugins/history.plugin.zsh"
 zplugin snippet "$ZDOTDIR/plugins/ls-aliases.plugin.zsh"
-zplugin snippet "$ZDOTDIR/plugins/pipenv.plugin.zsh"
+zplugin snippet "$ZDOTDIR/plugins/git.plugin.zsh"
+zplugin ice if"(( $+commands[rsync] ))"; zplugin snippet "$ZDOTDIR/plugins/cp-mv-safe.plugin.zsh"
+zplugin ice if"(( $+commands[pipenv] ))"; zplugin snippet "$ZDOTDIR/plugins/pipenv.plugin.zsh"
 zplugin ice if"[[ $OSTYPE == darwin* ]]"; zplugin snippet "$ZDOTDIR/plugins/homebrew.plugin.zsh"
 
 # github-plugins
 source $ZDOTDIR/zplugins.zsh
+
